import { readFile } from "node:fs/promises";
import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

test("formal design prototype fits the viewport and mirrors dialog and chart controls", async ({ page }) => {
  const markup = await readFile(new URL("../../docs/design/backtest-ui.html", import.meta.url), "utf8");
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto("about:blank");
  await page.setContent(`<html lang="ja"><head><title>Workbench reference</title></head><body>${markup}</body></html>`);
  for (const [width, height] of [[1920, 1080], [1440, 900], [1280, 720], [320, 700]]) {
    await page.setViewportSize({ width, height });
    const geometry = await page.evaluate(() => ({ width: innerWidth, height: innerHeight, scrollWidth: document.documentElement.scrollWidth, scrollHeight: document.documentElement.scrollHeight }));
    expect(geometry.scrollWidth).toBeLessThanOrEqual(width);
    if (width >= 768) expect(geometry.scrollHeight).toBeLessThanOrEqual(height + 1);
    const chartWidths = await page.locator(".chart-figure svg, .date-axis-row svg").evaluateAll((nodes) => nodes.map((node) => node.getBoundingClientRect().width));
    expect(chartWidths).toHaveLength(4);
    expect(Math.max(...chartWidths) - Math.min(...chartWidths)).toBeLessThanOrEqual(1);
    await expect(page.locator(".compact-indicator figcaption")).toHaveCount(0);
    await expect(page.locator(".chart-figure figcaption")).toHaveCount(0);
    await expect(page.locator(".chart-core-readout-row button[data-highlight]")).toHaveCount(2);
    const cursorLines = page.locator(".compact-indicator .cursor-example line");
    await expect(cursorLines).toHaveCount(2);
  }
  await page.setViewportSize({ width: 1440, height: 900 });
  const toggle = page.locator("#prototype-config-toggle");
  await toggle.click();
  await expect(toggle).toHaveAttribute("aria-expanded", "false");
  await toggle.click();
  await page.locator("#prototype-open-settings").click();
  await expect(page.locator(".shared-dialog")).toBeVisible();
  await page.locator(".shared-dialog .dialog-done").click();
  await page.locator(".strategy-card-open").first().click();
  const dialog = page.locator(".strategy-dialog");
  await expect(dialog.getByRole("radiogroup")).toHaveCount(0);
  await expect(dialog.locator(".condition-add-select")).toHaveCount(0);
  const sell = dialog.getByRole("switch", { name: "売却", exact: true });
  await sell.click();
  await expect(dialog.locator("#prototype-exit-ratio")).toHaveValue("20");
  await expect(dialog.locator("#prototype-exit-ratio2")).toHaveValue("30");
  await expect(dialog.locator("#prototype-exit-ratio")).toHaveAttribute("max", "100");
  await expect(dialog.locator("#prototype-exit-ratio")).toHaveAttribute("step", "1");
  expect((await dialog.locator("#prototype-exit-low").boundingBox()).y).toBeCloseTo((await dialog.locator("#prototype-exit-ratio").boundingBox()).y, 0);
  await sell.click();
  const buy = dialog.getByRole("switch", { name: "買付", exact: true });
  await buy.click();
  await expect(buy).toHaveAttribute("aria-checked", "false");
  await page.keyboard.press("Escape");
  await expect(dialog).not.toBeVisible();
  const comparisonRows = page.locator('[data-panel="comparison"] tbody tr');
  const monthly = comparisonRows.filter({ hasText: "毎月定額積立" });
  await monthly.locator(".result-select").click();
  await expect(monthly).toHaveCSS("translate", "0px -1px");
  expect(await monthly.evaluate(node => getComputedStyle(node).boxShadow)).not.toBe("none");
  await monthly.locator(".result-select").click();
  await expect(monthly).toHaveCSS("translate", "0px");
  await expect(monthly).toHaveCSS("box-shadow", "none");
  const axe = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze();
  expect(axe.violations).toEqual([]);
  expect(errors).toEqual([]);
  await page.screenshot({ path: test.info().outputPath("formal-workbench-reference.png") });
});

test("the reference exposes readonly trade and data explanations with keyboard and focus return", async ({ page }) => {
  const markup = await readFile(new URL("../../docs/design/backtest-ui.html", import.meta.url), "utf8");
  await page.goto("about:blank");
  await page.setContent(`<html lang="ja"><head><title>Result explanations reference</title></head><body>${markup}</body></html>`);
  const dialog = page.locator(".prototype-inspector-dialog");
  const data = page.getByRole("button", { name: "保存データ", exact: true });
  await data.click();
  await expect(dialog).toContainText("Yahoo Finance");
  await page.keyboard.press("Escape");
  await expect(data).toBeFocused();
  await page.getByRole("tab", { name: "取引明細", exact: true }).click();
  const entry = page.locator('[data-panel="trades"] [data-inspector="trade"]').first();
  await entry.click();
  await expect(dialog).toContainText("2026-07-31");
  const explanation = await dialog.locator(".dialog-content").innerText();
  await page.keyboard.press("Escape");
  await expect(entry).toBeFocused();
  const marker = page.locator('.chart-figure [data-inspector="trade"]');
  await page.locator('.chart-strategy-readout').click();
  await marker.focus();
  await page.keyboard.press("Enter");
  expect(await dialog.locator(".dialog-content").innerText()).toBe(explanation);
  await page.setViewportSize({ width: 320, height: 700 });
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
  await page.keyboard.press("Escape");
  await expect(marker).toBeFocused();
});

test("the reference separates risk-free inputs from saved NAV performance", async ({ page }) => {
  const markup = await readFile(new URL("../../docs/design/backtest-ui.html", import.meta.url), "utf8");
  await page.goto("about:blank");
  await page.setContent(`<html lang="ja"><head><title>Performance reference</title></head><body>${markup}</body></html>`);
  await page.locator('[data-tab="performance"]').click();
  const panel = page.locator('[data-panel="performance"]');
  await expect(panel.locator(".performance-stat")).toHaveCount(11);
  await expect(panel.locator(".trading-cost-stat")).toHaveCount(4);
  await expect(panel.locator(".annual-performance-table tbody tr")).toHaveCount(1);
  await expect(panel.locator(".drawdown-episodes-table tbody tr")).toHaveCount(1);
  await panel.locator(".heatmap-cell").first().focus();
  await expect(panel.locator(".heatmap-detail")).toHaveText("2024-01 · 2.1234%");
  await page.keyboard.press("Tab");
  await expect(panel.locator(".heatmap-cell.is-negative")).toBeFocused();
  await expect(panel.locator(".heatmap-detail")).toHaveText("2024-02 · -1.2345%");
  const saved = await panel.innerText();
  await page.locator("#prototype-open-settings").click();
  await page.locator("#prototype-risk-free").fill("5");
  await expect(page.locator(".shared-dialog fieldset")).toHaveCount(5);
  await page.locator("#prototype-commission").fill("2");
  await page.locator("#prototype-fractional").click();
  await expect(page.locator("#prototype-fractional")).toHaveAttribute("aria-checked", "false");
  await page.locator(".shared-dialog .dialog-done").click();
  expect(await panel.innerText()).toBe(saved);
  await page.setViewportSize({ width: 320, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
});
