import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";

test("Ctrl and Cmd shortcuts reuse run/file actions and never escape editable modal guards", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await expect(page.locator(".run-submit-button")).toBeEnabled();
  let downloads = 0, choosers = 0, submissions = 0;
  page.on("download", () => downloads++);
  page.on("filechooser", () => choosers++);
  page.on("request", request => { if (request.method() === "POST" && request.url().endsWith("/api/v1/runs")) submissions++; });
  const strategyDownload = page.waitForEvent("download");
  await page.keyboard.press("Control+e");
  const strategy = JSON.parse(await readFile(await (await strategyDownload).path(), "utf8"));
  expect(strategy.type).toBe("strategy");
  strategy.draft.shared.run.startDate = "2024-02-01";
  strategy.draft.shared.run.endDate = "2024-03-01";
  const chooser = page.waitForEvent("filechooser");
  await page.keyboard.press("Meta+i");
  await (await chooser).setFiles({ name: "shortcuts.strategy.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(strategy)) });
  await expect(page.locator(".package-preview")).toBeVisible();
  await page.locator(".package-preview .button-primary").click();
  await expect(page.locator(".package-preview")).toHaveCount(0);
  await expect(page.locator(".run-submit-button")).toBeEnabled();
  await page.keyboard.press("Meta+Enter");
  await expect(page.locator(".run-submit-button")).toBeDisabled();
  await page.keyboard.press("Control+Enter");
  await expect(page.locator(".comparison-table tbody tr")).toHaveCount(3);
  await expect(page.locator(".run-submit-button")).toBeEnabled();
  expect(submissions).toBe(1);
  const secondStrategyDownload = page.waitForEvent("download");
  await page.locator(".brand-mark").click();
  await page.keyboard.press("Meta+e");
  const secondStrategy = JSON.parse(await readFile(await (await secondStrategyDownload).path(), "utf8"));
  expect(secondStrategy.type).toBe("strategy");
  expect(secondStrategy.draft.strategies).toHaveLength(1);
  expect(secondStrategy).not.toHaveProperty("result");
  expect(downloads).toBe(2);
  expect(choosers).toBe(1);
  await page.locator(".shared-settings-open-button").click();
  const dialog = page.locator(".shared-settings-dialog");
  await dialog.locator('[data-parameter-key="contribution.amount"]').fill("-1");
  for (const combo of ["Control+Enter", "Meta+e", "Control+i"]) await page.keyboard.press(combo);
  await dialog.locator(".dialog-done").focus();
  for (const combo of ["Meta+Enter", "Control+e", "Meta+i"]) await page.keyboard.press(combo);
  expect(submissions).toBe(1);
  expect(downloads).toBe(2);
  expect(choosers).toBe(1);
  await page.keyboard.press("Escape");
  await expect(dialog).toBeVisible();
  await expect(dialog.locator('[data-parameter-key="contribution.amount"]')).toHaveAttribute("aria-invalid", "true");
  await dialog.locator('[data-parameter-key="contribution.amount"]').fill("100");
  await dialog.locator(".dialog-done").click();
  await expect(dialog).toHaveCount(0);
  await expect(page.locator(".shared-settings-open-button")).toBeFocused();
});
